# Generated by Django 5.1.2 on 2024-11-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user_for',
            new_name='used_for',
        ),
    ]
